server:
  port: 8080
  tomcat:
    url-encoding: utf-8

spring:
  datasource:
    name: zcc
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/zcc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&'
    username: 'root'
    password: '123456'
    # 使用hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: 'DatebookHikariCP'
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: 'SELECT 1'

#  security:
#    basic:
#      enabled: false
#  management:
#    security:
#      enabled: false
   
mybatis:
#  typeAliasesPackage: com.ytt.aaron_demo.po
  mapper-locations: classpath*:mapper/*.xml
